### ISSUE TITLE
Item frames cannot be broken by punching

### ISSUE THREAD

**Issue by walkersgaming** [CivMC/Citadel#19]
When placing item frames on a block unreinforced or reinforced, they cannot be broken by punching. The same applies when trying to remove an item from an item frame. They can however be broken by smothering with a block or breaking the block they're on

**Comment by Diet-Cola** [comment]
Does it say any message when trying to break it?

**Comment by walkersgaming** [comment]
> Does it say any message when trying to break it?

No, nothing

**Comment by Diet-Cola** [comment]
https://i.imgur.com/U0QRZq8.gif

**Comment by walkersgaming** [comment]
https://i.imgur.com/ViDyDvN.mp4

Using version 5.0.0-SNAPSHOT if that matters

**Comment by wingzero54** [comment]
Can confirm I have consistently had this issue and many other reporting as well, still a problem

**Comment by Aleksey-Terzi** [comment]
This issue is in Finale
Was reproduced and fixed
